### PR TITLE
Thanks for great Image Picker Controller..

### PR DESCRIPTION
**Pull request by oskarirauta**
But I wanted to make it a bit more.. Like picker that is used on most mainstream applications, so I started to make changes to make it look and behave more like picker of Facebook application's picker..

So I am not sure if you want to merge with my changes, but atleast wanted to give you a possibility to check out what I made.

Some code could be written better, there are also some "dirty" solutions, and there's one rare bug - selecting images should be limited to 99, but that's quite easy, just forgot to do it.. Maybe later.

And as your solution does not use xib's at all, I am a bit shamed that I went that road and set it to use xib for group popup.. But I never before had done a popup, so it was enough work there to make it actually work, tuning can always be done afterwards..

Anyway, tell me what you think of it, is this any good..?

### CODE REVIEW

**Comment by oskarirauta** [comment]
Bug I mentioned has now been fixed, I also made some more styling, nib file no longer is necessary....

**Comment by zhangao0086** [comment]
Thanks for your code! I know that you made work now. But much difference with the current style, I think we can implement a FB style Picker in a new project, do you?

**Comment by oskarirauta** [comment]
Sure we can. As you wrote the core of the picker, do you wish to host it under your account, or under my account? As far as I know, we can form a team, so both can commit to project.

What do you think of a picker using this style in overall?

**Comment by oskarirauta** [comment]
I can create the repository..

**Pull request closed without merging**
