### PR TITLE
Behavior when you click on the image already has exceeded the maximum…

### PR DESCRIPTION
**Pull request by ParkGwangBeom**
… limit #112

### CODE REVIEW

**Comment by zhangao0086** [comment]
Sorry for the late response...
Thanks for your commit! In the `3.2.0`, I've added an UIlAertView on max limit reach. 
Please check it :)

**Comment by zhangao0086** [comment]
Let me know if you have any questions :)

**Comment by seifeet** [comment]
zhangao0086 I believe this commit solves the following problem:
1) Camera is not available
2) click on the camera image
3) an error pops-up "Max photos limit reached" (even though no photos were selected)

The problem is in:
DKAssetGroupDetailVC / cameraCellForIndexPath

A different error message should be presented if the camera is not there.

Thanks!

**Comment by zhangao0086** [comment]
Hi @seifeet 
In the latest version, I've added a new API: `imagePickerControllerDidReachMaxLimit`

image

**Comment by seifeet** [comment]
Thanks for the fast reply!
May be my thinking is wrong but to me it seems like imagePickerControllerDidReachMaxLimit should not even be called if a camera is not present. Not a big deal, just a little confusing.

**Comment by zhangao0086** [comment]
@seifeet  I think I understand your question now. If a camera is not available, don't pops-up "Max photos limit reached".
```swift
cell.didCameraButtonClicked = { [unowned self] in
	if UIImagePickerController.isSourceTypeAvailable(.Camera) {
		if self.imagePickerController.selectedAssets.count < self.imagePickerController.maxSelectableCount  {
			self.imagePickerController.presentCamera()
		} else {
			self.imagePickerController.UIDelegate.imagePickerControllerDidReachMaxLimit(self.imagePickerController)
		}
	}
}
```

What do you think?

**Comment by seifeet** [comment]
Yes, that fixes it. Thank you.

**Comment by zhangao0086** [comment]
Closing this thread.

**Pull request closed without merging**
