### PR TITLE
refactor: example updated to listen asset selection/deselection clicks

### PR DESCRIPTION
**Pull request by preetamjadakar**
We may need to handle asset selection/deselection clicks for more customization, this PR is related to https://github.com/zhangao0086/DKImagePickerController/issues/612, https://github.com/zhangao0086/DKImagePickerController/issues/487, and https://github.com/zhangao0086/DKImagePickerController/issues/476

### CODE REVIEW

**Comment by zhangao0086** [comment]
Thanks for your PR!!!

**Comment by preetam-nihilent** [comment]
Thanks @zhangao0086

**Comment by preetamjadakar** [comment]
Thanks @zhangao0086, for accepting the PR.

**Comment by zhangao0086** [comment]
@preetamjadakar You're welcome 😄

**Pull request merged**
