### PR TITLE
Update Line 222 and the following to make it compile with Xcode 8 beta 5

### PR DESCRIPTION
**Pull request by hyouuu**

### CODE REVIEW

**Comment by zhangao0086** [comment]
Thanks!

**Comment by zhangao0086** [comment]
Could you make it compile with Xcode 8 beta 6?

**Comment by hyouuu** [comment]
Ah didn't know beta 6 came out so fast - will do!

**Comment by hyouuu** [comment]
Mmm I keeps getting segment fault 11 error on beta 6 - mind giving it a try?

**Comment by zhangao0086** [comment]
I'll try to fix it this weekend.

**Pull request merged**
