### PR TITLE
Costume Camera Request Issue #79 

### PR DESCRIPTION
**Pull request by AdventuresOfMar**
This is  a pull request in hopes of figuring out the parameters for using a costume camera outside of DKCamera from issue #79

### CODE REVIEW

**Comment by zhangao0086** [comment]
Does not any commits?

**Comment by chazmo03** [comment]
@zhangao0086, do you have any thoughts on a good way to implement a custom camera or including the option to capture video instead of photos? I would love to use your picker but like @AdventuresOfMar, I need the camera option to capture video.

**Comment by zhangao0086** [comment]
@chazmo03  I have little idea about this:https://github.com/zhangao0086/DKImagePickerController/pull/84

**Comment by zhangao0086** [comment]
In `3.1.0`, I've added support for custom camera. 
Simply implement the `DKImagePickerControllerUIDelegate` protocol or inherit the `DKImagePickerControllerDefaultUIDelegate` class.
The following is the default implementation:
```swift
public class DKImagePickerControllerDefaultUIDelegate: NSObject, DKImagePickerControllerUIDelegate {
	
	public func imagePickerControllerCreateCamera(imagePickerController: DKImagePickerController, didCancel: (() -> Void), didFinishCapturingImage: ((image: UIImage) -> Void)) -> UIViewController {
		
		let camera = DKCamera()
		
		camera.didCancel = { () -> Void in
			didCancel()
		}
		
		camera.didFinishCapturingImage = { (image) in
			didFinishCapturingImage(image: image)
		}
		self.checkCameraPermission(camera)
	
		return camera
	}
	
	private func checkCameraPermission(camera: DKCamera) {
		func cameraDenied() {
			dispatch_async(dispatch_get_main_queue()) {
				let permissionView = DKPermissionView.permissionView(.Camera)
				camera.cameraOverlayView = permissionView
			}
		}
		
		func setup() {
			camera.cameraOverlayView = nil
		}
		
		DKCamera.checkCameraPermission { granted in
			granted ? setup() : cameraDenied()
		}
	}
	
	public func imagePickerControllerCameraImage() -> UIImage {
		return DKImageResource.cameraImage()
	}
}
```

**Comment by zhangao0086** [comment]
Closing...

**Comment by ThePhantomKid** [comment]
this is incredible! I re-downloaded the source code in attempts to understand this implementation but your custom camera class isn't too helpful. What methods do we put in our custom camera class to confirm it to DKImagePickerControllerUIDelegate protocol

**Comment by zhangao0086** [comment]
@ThePhantomKid 
You have to provide a view controller(Camera) and call `didCancel` and `didFinishCapturingImage` at the proper time. I'll update the demo project later.

**Comment by chazmo03** [comment]
Thank you for the quick and detailed reply @zhangao0086 and sorry for my delayed response. I think it's great that you're moving in the direction of using a delegate to handle this functionality instead of having a bunch of functions on the controller itself. That said, your delegate methods still only allow for still images, not video. For my own use, I just [added a new method](https://github.com/chazmo03/DKImagePickerController/commit/369d5dbadeda404b0a7ff7ce3cd0c46cd71038d1) to be called when the user clicks the camera button. This allows me to to use whatever camera I want. My app then uses the camera's delegates and doesn't have to rely on the delegates from DKImagePickerController for when a photo or a video is taken. It separates the choosing functionality from the capturing functionality.

**Comment by zhangao0086** [comment]
Hi @chazmo03 
In the latest version, I've added video support for custom camera: https://github.com/zhangao0086/DKImagePickerController/pull/102
And added an example using `UIImagePickerController`.

Please let me know your thoughts :)

**Comment by chazmo03** [comment]
Thanks @zhangao0086. I just took a look at the code and it looks like a nice improvement. I won't have the opportunity to pull this new version into my app for a while, but based on the code, it looks like it should work.

**Comment by zhangao0086** [comment]
@chazmo03  Let me know if you have any questions!

**Pull request closed without merging**
