### PR TITLE
Swift4 fix

### PR DESCRIPTION
**Pull request by JettF**
My coworker and I figured out why the project was not building for us in swift 4. The version number was set to 3.2 instead of 4. This PR fixes that.

### CODE REVIEW

**Comment by zhangao0086** [comment]
Thanks for the PR!

**Comment by JettF** [comment]
You're welcome! Thank you for pulling it in so quickly!

**Comment by JettF** [comment]
@zhangao0086 can you push a patch version soon?

**Comment by zhangao0086** [comment]
Updated.

**Pull request merged**
