### PR TITLE
[WIP] Support SwiftPM

### PR DESCRIPTION
**Pull request by zrn-ns**
Issue: https://github.com/zhangao0086/DKImagePickerController/issues/652

Added support of Swift Package Manager.

Before merging, needs to update dependency url.

### CODE REVIEW

**Comment by julianoterres** [comment]
Guys, can you approve and merge? I would like to be able to use the lib with SPM

**Comment by zhangao0086** [comment]
Thanks for your PR!!! Merged in, update the url later~

**Comment by robvandijk** [comment]
I guess the url has not been updated yet? When trying to add this package I currently get error
`Package.swift does not exist`

**Comment by seanodonnell-udisc** [comment]
^ Same here
Screen Shot 2023-05-16 at 10 08 09 AM

**Pull request merged**
