### PR TITLE
Swift3

### PR DESCRIPTION
**Pull request by JackieQi**
Merged master and updated travis. Please take a look.

### CODE REVIEW

**Comment by zhangao0086** [comment]
Hi @JackieQi 
I've just read the [Travis CI Document](https://docs.travis-ci.com/user/osx-ci-environment/#Xcode-8):

> Our Xcode 8beta4 images have the following SDKs preinstalled:
> 
> - macosx10.11
> - iphoneos10.0
> - iphonesimulator10.0
> - appletvos10.0
> - appletvsimulator10.0
> - watchos3.0
> - watchsimulator3.0

> The Xcode 8beta4 image also comes with the following simulators:
> - iOS 10.0
> - watchOS 3.0
> - tvOS 10.0

Could you replace `iphonesimulator9.3` with `iphonesimulator10.0` in the `.travis.yml` file?

**Comment by JackieQi** [comment]
@zhangao0086 I just did. Thanks. I have never used Travis myself.

**Comment by zhangao0086** [comment]
Thank you so much for your effort :)

**Comment by zhangao0086** [comment]
I'll merge it and then trying to fix Travis CI. Thanks for your PR!!! 🍻 🍻 🍻

**Comment by JackieQi** [comment]
You're so welcome. Thanks for your repo.

**Pull request merged**
