### PR TITLE
Add more customization of colors and fonts

### PR DESCRIPTION
**Pull request by kiley1323**
Added the capability to change the background color of the collection view, the tint color of the image that denotes an object was selected, and the font and color of the text used to show the order of the images selected. This way, people can customize their projects even further.

### CODE REVIEW

**Comment by kiley1323** [comment]
apologies on any naming conventions!

**Comment by zhangao0086** [comment]
`numberFnt`? typo?

**Comment by kiley1323** [comment]
good catch sorry about that!

**Comment by tzm41** [comment]
I totally agree that this is a good thing to be merged!

**Comment by zhangao0086** [comment]
Thanks for your PR!

**Pull request merged**
