### PR TITLE
Permission view colors

### PR DESCRIPTION
**Pull request by jmilillo**
We needed a way to change the colors on the PermissionView when the user has denied access to the photos or camera.

Added a colors object that contains the existing colors.  This object can be passed into the permission view, otherwise it uses the defaults.

### CODE REVIEW

**Comment by ferico55** [comment]
can you please create a pull request to develop branch instead?

**Comment by jmilillo** [comment]
@ferico55 I have migrated my changes over and I added a couple accessibility identifiers to assist with UI tests we wrote.   Please re-review!

**Comment by ferico55** [comment]
looks good for me, but I'll give the final decision of merging back to @zhangao0086

**Comment by jmilillo** [comment]
@zhangao0086 A decision either way on this PR would be welcome.

**Comment by zhangao0086** [comment]
Thanks!

**Pull request merged**
